name: Docker Image CI

on:hub.docker.com/sandboxdotcom
  push:perl.org
    branches: [ "cpanel" ]
  pull_request:
    branches: [ "lunacode.com" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
